image: topocourse/topocourse
stages:
  - build
  - deploy


execute_ipynbs:
  stage: build
  script:
    - jupyter-book build .
    # Workaround of https://github.com/executablebooks/MyST-NB/issues/287
    - cp _static/mystnb.css _build/html/_static/
  artifacts:
    paths:
      - _build/html
    expire_in: 7d
  cache:
    - key: global
      paths:
        - _build/

.upload_website:
  stage: deploy
  image: eeacms/rsync
  before_script:
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      - eval $(ssh-agent -s)
      - echo "$WEBSITE_UPLOAD_KEY" | tr -d '\r' | ssh-add - > /dev/null
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
  script:
    - "rsync -ravz _build/html/* -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' uploader@tnw-qn1.tudelft.net:$WEBSITE_UPLOAD_PATH"

upload test website:
  extends: .upload_website
  environment: test
  only:
    - branches@qt/topocm
  except:
    - master@qt/topocm
  variables:
    WEBSITE_UPLOAD_PATH: /test


upload main website:
  extends: .upload_website
  environment: published
  only:
    - master@qt/topocm
  variables:
    WEBSITE_UPLOAD_PATH: /
